# https://github.com/mperham/sidekiq/blob/master/examples/config.yml

#   sidekiq -C config/sidekiq.yml
---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: 25
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30
:queues:
  - [critical, 3]
  - [default, 2]
  - [low, 1]
